"""empty message

Revision ID: 469ad64df3df
Revises: cfe773fa397d
Create Date: 2022-10-12 10:36:46.561727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469ad64df3df'
down_revision = 'cfe773fa397d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'character', 'planet', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'planet_id')
    # ### end Alembic commands ###
