"""empty message

Revision ID: 8730cda0cd0d
Revises: 469ad64df3df
Create Date: 2022-10-12 10:41:39.648951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8730cda0cd0d'
down_revision = '469ad64df3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('character_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite', 'character', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'character_id')
    # ### end Alembic commands ###
