"""empty message

Revision ID: b70ef3595877
Revises: 8730cda0cd0d
Create Date: 2022-10-12 10:45:13.147314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70ef3595877'
down_revision = '8730cda0cd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite', 'planet', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'planet_id')
    # ### end Alembic commands ###
