"""empty message

Revision ID: cfe773fa397d
Revises: e6ef1f23c612
Create Date: 2022-10-12 09:15:06.071988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfe773fa397d'
down_revision = 'e6ef1f23c612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'character', ['name'])
    op.alter_column('planet', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('planet', 'terrain',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('planet', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'planet', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='unique')
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'terrain',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'character', type_='unique')
    # ### end Alembic commands ###
